In [1]:
import numpy as np

In [2]:
class NeuralNetwork():
    def __init__(self):
        # seeding for random number generation
        np.random.seed(1)
        #converting weights to a 3 by 1 matrix with values from -1 to 1 and mean of 0
        self.synaptic_weights = 2 * np.random.random((3, 1)) - 1

    def sigmoid(self, x):
        #applying the sigmoid function
        return 1 / (1 + np.exp(-x))

    def sigmoid_derivative(self, x):
        #computing derivative to the Sigmoid function
        return x * (1 - x)

    def train(self, training_inputs, training_outputs, training_iterations):
        #training the model to make accurate predictions while adjusting weights continually
        for iteration in range(training_iterations):
            #siphon the training data via  the neuron
            output = self.think(training_inputs)
            #computing error rate for back-propagation
            error = training_outputs - output
            #performing weight adjustments
            adjustments = np.dot(training_inputs.T, error * self.sigmoid_derivative(output))

            self.synaptic_weights += adjustments

    def think(self, inputs):
        #passing the inputs via the neuron to get output   
        #converting values to floats
        inputs = inputs.astype(float)
        output = self.sigmoid(np.dot(inputs, self.synaptic_weights))
        return output

In [4]:
neural_network = NeuralNetwork()

In [5]:
print("Menghasilkan Weights Pertama Secara Random: ")
print(neural_network.synaptic_weights)

Menghasilkan Weights Pertama Secara Random: 
[[-0.16595599]
 [ 0.44064899]
 [-0.99977125]]


In [8]:
#training data consisting of 4 examples--3 input values and 1 output
training_inputs = np.array([[0,0,1], #1 0 0 1 0
                            [1,1,1], #2 1 1 1 1
                            [1,0,1], #3 1 0 1 1
                            [0,1,1]])#4 0 1 1 0

training_outputs = np.array([[0,1,1,0]]).T

training_inputs

array([[0, 0, 1],
       [1, 1, 1],
       [1, 0, 1],
       [0, 1, 1]])

In [9]:
training_outputs

array([[0],
       [1],
       [1],
       [0]])

In [12]:
#training taking place
neural_network.train(training_inputs, training_outputs, 20000)

In [13]:
print("Weights Akhir Setelah Proses Training: ")
print(neural_network.synaptic_weights)

Weights Akhir Setelah Proses Training: 
[[11.08357409]
 [-0.20536384]
 [-5.33695387]]


In [15]:
user_input_1 = str(input("Masukan 1: "))
user_input_2 = str(input("Masukan 2: "))
user_input_3 = str(input("Masukan 3: "))

print("Data Input Terbaru: ", user_input_1, user_input_2, user_input_3)
print("Output: ")
print(neural_network.think(np.array([user_input_1, user_input_2, user_input_3])))

Masukan 1:  1
Masukan 2:  1
Masukan 3:  0


Data Input Terbaru:  1 1 0
Output: 
[0.99998114]


In [ ]:
if __name__ == "__main__":
    #initializing the neuron class
    neural_network = NeuralNetwork()
    
    print("Menghasilkan Weights Pertama Secara Random: ")
    print(neural_network.synaptic_weights)
    
    #training data consisting of 4 examples--3 input values and 1 output
    training_inputs = np.array([[0,0,1],
                                [1,1,1],
                                [1,0,1],
                                [0,1,1]])

    training_outputs = np.array([[0,1,1,0]]).T
    
    #training taking place
    neural_network.train(training_inputs, training_outputs, 20000)

    print("Weights Akhir Setelah Proses Training: ")
    print(neural_network.synaptic_weights)

    user_input_1 = str(input("Masukan 1: "))
    user_input_2 = str(input("Masukan 2: "))
    user_input_3 = str(input("Masukan 3: "))
    
    print("Data Input Terbaru: ", user_input_1, user_input_2, user_input_3)
    print("Output: ")
    print(neural_network.think(np.array([user_input_1, user_input_2, user_input_3])))